config/routes.rb
Rails.application.routes.draw do

  resources :auctions do
    resources :bids
  end

  root 'auctions#index'

end

app/models/auction.rb
class Auction < ActiveRecord::Base

  has_many :bids

  validates :title, presence: true
  validates :body, presence: true
  validates :end_time, presence: true
  validates :reserve, presence: true, numericality: true

  validate :end_time_is_in_future

  def end_time_is_in_future
    errors.add(:end_time, "can't be in the past") if
      !end_time.blank? && end_time < Date.today
  end

  include AASM

  # we put all the states and transitions in the `aasm` block
  aasm whiny_transitions: false do
    state :published, initial: true
    state :reserve_met
    state :reserve_not_met
    state :won
    state :closed

    event :was_won do
      transitions from: :reserve_met, to: :won
    end

    event :reserve_was_met do
      transitions from: :published, to: :reserve_met
    end

    event :reserve_was_not_met do
      transitions from: :published, to: :reserve_not_met
    end

    event :close do
      transitions from: [:reserve_not_met, :published], to: :closed
    end
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :auction

  validates :amount, presence: true, numericality: true
  #validates_numericality_of :amount, :greater_than => Proc.new{Bid.last}

  validate :greater_than_current_price

  def greater_than_current_price
    unless self.auction.nil?
      errors.add(:amount, "must be greater than current price") if
        !amount.blank? && amount < self.auction.current_price
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

  def index
    @auctions = Auction.all
  end

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new allowed_auction_params
    if @auction.save
      redirect_to auction_path(@auction)
    else
      render :new
    end
  end

  def show
    @bid = Bid.new
    @auction = Auction.find params[:id]
  end

  def edit
  end

  private

  def allowed_auction_params
    params.require(:auction).permit(:title, :body, :end_time, :reserve)
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  def create
    @auction = Auction.find params[:auction_id]
    @bid   = @auction.bids.new bid_params
    if @bid.amount && @bid.amount > @auction.current_price
      a = Auction.find(@auction)
      a.current_price = @bid.amount
      a.save
    end
    if @bid.amount && @bid.amount > @auction.reserve.to_f
      a = Auction.find(@auction)
      a.reserve_was_met
      a.save
    end
    if @bid.save
      redirect_to auction_path(@auction)
    else
      render "/auctions/show"
    end
  end

  private
  def bid_params
    params.require(:bid).permit(:amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/auctions/edit.html.slim
h1 Auctions#edit
p Find me in app/views/auctions/edit.html.slim

app/views/auctions/index.html.slim
.col-md-4.col-md-offset-3
  h2
    =link_to "Create new auction", new_auction_path
  br
  h1 All Auctions
  
  -@auctions.each do |a|
    h3
      =link_to a.title, auction_path(a)
    

app/views/auctions/new.html.slim
.col-md-4.col-md-offset-3
  =simple_form_for @auction do |f|
    =f.input :title
    =f.input :body
    =f.input :end_time
    =f.input :reserve
    =f.submit

app/views/auctions/show.html.slim
.col-sm-4.col-md-offset-3
  h3
    =link_to "Home", root_path
  h2
   =@auction.title
  h3
    | current price #{number_to_currency(@auction.current_price, :unit => "$")}
  p 
    h3 Description
    =@auction.body
  h3 Ends at
  =@auction.end_time
  h3 Reserve price
  =number_to_currency(@auction.reserve, :unit => "$")
  
  -if !@auction.reserve_met?
    h3 Do some bidding
    
    =simple_form_for [@auction, @bid] do |f|
      =f.input :amount, as: :string
      =f.submit
    
  h3 Bids
  
  -@auction.bids.order("created_at DESC").each do |b|
    =number_to_currency(b.amount, :unit => "$")
    br

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Biddr
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container-fluid
      -if flash[:alert]
        =flash[:alert]
      = yield